# Generated by Django 2.1.4 on 2020-04-04 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200404_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 16, 31, 43, 477277), verbose_name='date published'),
        ),
    ]
