# Generated by Django 2.1.5 on 2020-04-16 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200416_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 22, 57, 47, 630795), verbose_name='date published'),
        ),
    ]
