# Generated by Django 2.1.5 on 2020-04-18 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200416_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 22, 12, 11, 983566), verbose_name='date published'),
        ),
    ]
